version: 2
defaults: &defaults
  docker:
    - image: tapsellorg/android-sdk:v3.1.0

jobs:

  build:
    <<: *defaults

    steps:
      - checkout
      - run:
            name: Build APK
            command: ./gradlew assembleDebug


  playStorePublish:
      <<: *defaults

      steps:
        - checkout
        - run:
            name: get key store
            command: curl https://storage.backtory.com/$KEY_STORE_LINK --output ./app/metrix_sample.jks

        - run:
            name: get play service jsonFile
            command: echo $PLAY_SERVICE_JSON > ./app/key.json

        - run:
            name: publish to Play Store
            command: ./gradlew publishApkRelease

workflows:
  version: 2

  build:
    jobs:
      - build

  publish:
    jobs:
      - hold:
          type: approval

      - playStorePublish:
          requires:
            - hold